### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by TadhgEomonn** [altairwei/Stoneshard-UniqueItemMarket#1]
[13:38:27 ERR] Something went wrong
System.IO.FileNotFoundException:
File name: 'UndertaleModLib, Version=0.6.1.0, Culture=neutral, PublicKeyToken=null'
   at UniqueItemMarket.UniqueItemMarket.PatchMod()
   at ModShardLauncher.ModLoader.PatchMods()
   at ModShardLauncher.ModLoader.PatchFile()
   at ModShardLauncher.Controls.ModInfos.Save_Click(Object sender, EventArgs e)
[13:38:27 INF] Failed patching vanilla

Plus: [13:55:36 INF] Cannot find the icon.png associated to UniqueItemMarket.sml

**Comment by altairwei** [comment]
My bad, I will fix this soon.

**Comment by altairwei** [comment]
Done. Please download it again.

**Comment by TadhgEomonn** [comment]
Getting the same error with the update.

[20:40:24 ERR] Something went wrong
System.IO.FileNotFoundException:
File name: 'UndertaleModLib, Version=0.6.1.0, Culture=neutral, PublicKeyToken=null'
   at UniqueItemMarket.UniqueItemMarket.PatchMod()
   at ModShardLauncher.ModLoader.PatchMods()
   at ModShardLauncher.ModLoader.PatchFile()
   at ModShardLauncher.Controls.ModInfos.Save_Click(Object sender, EventArgs e)
[20:40:24 INF] Failed patching vanilla

**Comment by TadhgEomonn** [comment]
The file in the download is dated yesterday. Are you sure you uploaded the fixed file?

**Comment by altairwei** [comment]
> The file in the download is dated yesterday. Are you sure you uploaded the fixed file?

Yes, I have uploaded the new file. Maybe you downloaded it too early? A new file hasn't been reviewed by NexusMod yet?

**Comment by altairwei** [comment]
I see from the stats that no one has downloaded the new file yet.

**Comment by altairwei** [comment]
I really did upload the wrong file again. xD

**Comment by altairwei** [comment]
The most up-to-date file is now ready.

**Comment by TadhgEomonn** [comment]
msl completed without error.
